# Generated by Django 3.0 on 2022-11-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Оформлен', 'Заказ оформлен'), ('В процессе', 'Заказ готовится'), ('Готов', 'Заказ готов')], default='Заказ оформлен', max_length=25),
        ),
    ]
