# Generated by Django 3.0 on 2022-11-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
