# Generated by Django 3.0 on 2022-10-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='register_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orders_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='customuser',
            index_together={('id', 'slug')},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
