# Generated by Django 3.0 on 2022-11-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='email',
            new_name='username',
        ),
    ]
