# Generated by Django 3.0 on 2022-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterIndexTogether(
            name='customuser',
            index_together={('id', 'username')},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
    ]
